import React from 'react';
import { configure, shallow, mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import Days from './Days';

configure({ adapter: new Adapter() });

describe('<Days />', () => {

  const data = [
    {
      "day":"Sun",
      "data":[
        {
          "dt":1525003200,
          "main":{
            "temp":31.57,
            "temp_min":31.57,
            "temp_max":31.57,
            "pressure":985.56,
            "sea_level":1013.17,
            "grnd_level":985.56,
            "humidity":36,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10d"
            }
          ],
          "clouds":{
            "all":32
          },
          "wind":{
            "speed":5.25,
            "deg":17.5042
          },
          "rain":{
            "3h":0.12935
          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-04-29 12:00:00"
        },
        {
          "dt":1525014000,
          "main":{
            "temp":24.32,
            "temp_min":24.32,
            "temp_max":24.32,
            "pressure":988.15,
            "sea_level":1016.17,
            "grnd_level":988.15,
            "humidity":67,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10n"
            }
          ],
          "clouds":{
            "all":80
          },
          "wind":{
            "speed":3.41,
            "deg":6.0004
          },
          "rain":{
            "3h":0.27151
          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-04-29 15:00:00"
        },
        {
          "dt":1525024800,
          "main":{
            "temp":24.85,
            "temp_min":24.85,
            "temp_max":24.85,
            "pressure":986.47,
            "sea_level":1014.89,
            "grnd_level":986.47,
            "humidity":52,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10n"
            }
          ],
          "clouds":{
            "all":68
          },
          "wind":{
            "speed":1.67,
            "deg":97.5023
          },
          "rain":{
            "3h":0.06063
          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-04-29 18:00:00"
        }
      ]
    },
    {
      "day":"Mon",
      "data":[
        {
          "dt":1525035600,
          "main":{
            "temp":22.98,
            "temp_min":22.98,
            "temp_max":22.98,
            "pressure":986.04,
            "sea_level":1014.63,
            "grnd_level":986.04,
            "humidity":65,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10n"
            }
          ],
          "clouds":{
            "all":12
          },
          "wind":{
            "speed":3.86,
            "deg":165.507
          },
          "rain":{
            "3h":0.00516
          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-04-29 21:00:00"
        },
        {
          "dt":1525046400,
          "main":{
            "temp":21.49,
            "temp_min":21.49,
            "temp_max":21.49,
            "pressure":987.55,
            "sea_level":1016.04,
            "grnd_level":987.55,
            "humidity":73,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":2.32,
            "deg":185
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-04-30 00:00:00"
        },
        {
          "dt":1525057200,
          "main":{
            "temp":26.45,
            "temp_min":26.45,
            "temp_max":26.45,
            "pressure":990.01,
            "sea_level":1018.44,
            "grnd_level":990.01,
            "humidity":58,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.31,
            "deg":82.5
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-04-30 03:00:00"
        },
        {
          "dt":1525068000,
          "main":{
            "temp":34.32,
            "temp_min":34.32,
            "temp_max":34.32,
            "pressure":989.42,
            "sea_level":1017.55,
            "grnd_level":989.42,
            "humidity":35,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":5.66,
            "deg":113.502
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-04-30 06:00:00"
        },
        {
          "dt":1525078800,
          "main":{
            "temp":37.54,
            "temp_min":37.54,
            "temp_max":37.54,
            "pressure":987.11,
            "sea_level":1014.93,
            "grnd_level":987.11,
            "humidity":30,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.82,
            "deg":118.501
          },
          "rain":{
            "3h":0.00001000000000001
          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-04-30 09:00:00"
        },
        {
          "dt":1525089600,
          "main":{
            "temp":37.77,
            "temp_min":37.77,
            "temp_max":37.77,
            "pressure":985.87,
            "sea_level":1013.72,
            "grnd_level":985.87,
            "humidity":23,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":2.71,
            "deg":40.5043
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-04-30 12:00:00"
        },
        {
          "dt":1525100400,
          "main":{
            "temp":32.26,
            "temp_min":32.26,
            "temp_max":32.26,
            "pressure":987.49,
            "sea_level":1015.56,
            "grnd_level":987.49,
            "humidity":32,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.46,
            "deg":67.5003
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-04-30 15:00:00"
        },
        {
          "dt":1525111200,
          "main":{
            "temp":29.19,
            "temp_min":29.19,
            "temp_max":29.19,
            "pressure":988.63,
            "sea_level":1017.01,
            "grnd_level":988.63,
            "humidity":43,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.82,
            "deg":108.5
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-04-30 18:00:00"
        }
      ]
    },
    {
      "day":"Tue",
      "data":[
        {
          "dt":1525122000,
          "main":{
            "temp":26.8,
            "temp_min":26.8,
            "temp_max":26.8,
            "pressure":988.52,
            "sea_level":1016.88,
            "grnd_level":988.52,
            "humidity":52,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.01,
            "deg":106
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-04-30 21:00:00"
        },
        {
          "dt":1525132800,
          "main":{
            "temp":24.65,
            "temp_min":24.65,
            "temp_max":24.65,
            "pressure":989.49,
            "sea_level":1017.95,
            "grnd_level":989.49,
            "humidity":58,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":3.93,
            "deg":99.5007
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-01 00:00:00"
        },
        {
          "dt":1525143600,
          "main":{
            "temp":30.42,
            "temp_min":30.42,
            "temp_max":30.42,
            "pressure":991.19,
            "sea_level":1019.48,
            "grnd_level":991.19,
            "humidity":41,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.66,
            "deg":109.503
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-01 03:00:00"
        },
        {
          "dt":1525154400,
          "main":{
            "temp":37.38,
            "temp_min":37.38,
            "temp_max":37.38,
            "pressure":990.3,
            "sea_level":1018.27,
            "grnd_level":990.3,
            "humidity":31,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.71,
            "deg":125.003
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-01 06:00:00"
        },
        {
          "dt":1525165200,
          "main":{
            "temp":39.2,
            "temp_min":39.2,
            "temp_max":39.2,
            "pressure":987.95,
            "sea_level":1015.69,
            "grnd_level":987.95,
            "humidity":28,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":2.06,
            "deg":91.5001
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-01 09:00:00"
        },
        {
          "dt":1525176000,
          "main":{
            "temp":38.86,
            "temp_min":38.86,
            "temp_max":38.86,
            "pressure":986.6,
            "sea_level":1014.35,
            "grnd_level":986.6,
            "humidity":20,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":2.91,
            "deg":2.51096
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-01 12:00:00"
        },
        {
          "dt":1525186800,
          "main":{
            "temp":32.04,
            "temp_min":32.04,
            "temp_max":32.04,
            "pressure":988.14,
            "sea_level":1016.23,
            "grnd_level":988.14,
            "humidity":26,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":3.56,
            "deg":29.5018
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-01 15:00:00"
        },
        {
          "dt":1525197600,
          "main":{
            "temp":28.83,
            "temp_min":28.83,
            "temp_max":28.83,
            "pressure":989.33,
            "sea_level":1017.7,
            "grnd_level":989.33,
            "humidity":34,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.02,
            "deg":65.5004
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-01 18:00:00"
        }
      ]
    },
    {
      "day":"Wed",
      "data":[
        {
          "dt":1525208400,
          "main":{
            "temp":26.18,
            "temp_min":26.18,
            "temp_max":26.18,
            "pressure":988.78,
            "sea_level":1017.2,
            "grnd_level":988.78,
            "humidity":49,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":3.87,
            "deg":104.501
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-01 21:00:00"
        },
        {
          "dt":1525219200,
          "main":{
            "temp":25.04,
            "temp_min":25.04,
            "temp_max":25.04,
            "pressure":989.53,
            "sea_level":1017.98,
            "grnd_level":989.53,
            "humidity":56,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.21,
            "deg":115.5
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-02 00:00:00"
        },
        {
          "dt":1525230000,
          "main":{
            "temp":30.97,
            "temp_min":30.97,
            "temp_max":30.97,
            "pressure":991.22,
            "sea_level":1019.47,
            "grnd_level":991.22,
            "humidity":39,
            "temp_kf":0
          },
          "weather":[
            {
              "id":801,
              "main":"Clouds",
              "description":"few clouds",
              "icon":"02d"
            }
          ],
          "clouds":{
            "all":20
          },
          "wind":{
            "speed":4.51,
            "deg":127.001
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-02 03:00:00"
        },
        {
          "dt":1525240800,
          "main":{
            "temp":37.89,
            "temp_min":37.89,
            "temp_max":37.89,
            "pressure":991.18,
            "sea_level":1019.23,
            "grnd_level":991.18,
            "humidity":28,
            "temp_kf":0
          },
          "weather":[
            {
              "id":801,
              "main":"Clouds",
              "description":"few clouds",
              "icon":"02d"
            }
          ],
          "clouds":{
            "all":20
          },
          "wind":{
            "speed":4.67,
            "deg":145.002
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-02 06:00:00"
        },
        {
          "dt":1525251600,
          "main":{
            "temp":33.12,
            "temp_min":33.12,
            "temp_max":33.12,
            "pressure":990.25,
            "sea_level":1017.86,
            "grnd_level":990.25,
            "humidity":42,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10d"
            }
          ],
          "clouds":{
            "all":48
          },
          "wind":{
            "speed":2.57,
            "deg":52.5032
          },
          "rain":{
            "3h":0.428
          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-02 09:00:00"
        },
        {
          "dt":1525262400,
          "main":{
            "temp":33.16,
            "temp_min":33.16,
            "temp_max":33.16,
            "pressure":988.96,
            "sea_level":1017.17,
            "grnd_level":988.96,
            "humidity":33,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10d"
            }
          ],
          "clouds":{
            "all":56
          },
          "wind":{
            "speed":2.86,
            "deg":105.505
          },
          "rain":{
            "3h":0.2034
          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-02 12:00:00"
        },
        {
          "dt":1525273200,
          "main":{
            "temp":28.48,
            "temp_min":28.48,
            "temp_max":28.48,
            "pressure":990.38,
            "sea_level":1018.64,
            "grnd_level":990.38,
            "humidity":45,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10n"
            }
          ],
          "clouds":{
            "all":24
          },
          "wind":{
            "speed":3.46,
            "deg":57
          },
          "rain":{
            "3h":0.3751
          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-02 15:00:00"
        },
        {
          "dt":1525284000,
          "main":{
            "temp":24.31,
            "temp_min":24.31,
            "temp_max":24.31,
            "pressure":991.64,
            "sea_level":1019.88,
            "grnd_level":991.64,
            "humidity":65,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10n"
            }
          ],
          "clouds":{
            "all":36
          },
          "wind":{
            "speed":2.66,
            "deg":70.0011
          },
          "rain":{
            "3h":0.2554
          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-02 18:00:00"
        }
      ]
    },
    {
      "day":"Thu",
      "data":[
        {
          "dt":1525294800,
          "main":{
            "temp":22.19,
            "temp_min":22.19,
            "temp_max":22.19,
            "pressure":991.05,
            "sea_level":1019.4,
            "grnd_level":991.05,
            "humidity":75,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10n"
            }
          ],
          "clouds":{
            "all":44
          },
          "wind":{
            "speed":2.21,
            "deg":99.5005
          },
          "rain":{
            "3h":0.1555
          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-02 21:00:00"
        },
        {
          "dt":1525305600,
          "main":{
            "temp":21.61,
            "temp_min":21.61,
            "temp_max":21.61,
            "pressure":991.91,
            "sea_level":1020.54,
            "grnd_level":991.91,
            "humidity":79,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.77,
            "deg":107.002
          },
          "rain":{
            "3h":0.20645
          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-03 00:00:00"
        },
        {
          "dt":1525316400,
          "main":{
            "temp":25.49,
            "temp_min":25.49,
            "temp_max":25.49,
            "pressure":993.69,
            "sea_level":1022.06,
            "grnd_level":993.69,
            "humidity":65,
            "temp_kf":0
          },
          "weather":[
            {
              "id":802,
              "main":"Clouds",
              "description":"scattered clouds",
              "icon":"03d"
            }
          ],
          "clouds":{
            "all":32
          },
          "wind":{
            "speed":5.91,
            "deg":113.005
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-03 03:00:00"
        },
        {
          "dt":1525327200,
          "main":{
            "temp":34.3,
            "temp_min":34.3,
            "temp_max":34.3,
            "pressure":993.1,
            "sea_level":1021.27,
            "grnd_level":993.1,
            "humidity":39,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":6.37,
            "deg":122.502
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-03 06:00:00"
        },
        {
          "dt":1525338000,
          "main":{
            "temp":35.79,
            "temp_min":35.79,
            "temp_max":35.79,
            "pressure":990.55,
            "sea_level":1018.55,
            "grnd_level":990.55,
            "humidity":35,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10d"
            }
          ],
          "clouds":{
            "all":36
          },
          "wind":{
            "speed":4.33,
            "deg":129.002
          },
          "rain":{
            "3h":0.1416
          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-03 09:00:00"
        },
        {
          "dt":1525348800,
          "main":{
            "temp":26.65,
            "temp_min":26.65,
            "temp_max":26.65,
            "pressure":991.27,
            "sea_level":1019.09,
            "grnd_level":991.27,
            "humidity":61,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10d"
            }
          ],
          "clouds":{
            "all":32
          },
          "wind":{
            "speed":5.06,
            "deg":58.5016
          },
          "rain":{
            "3h":1.0448
          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-03 12:00:00"
        },
        {
          "dt":1525359600,
          "main":{
            "temp":24.89,
            "temp_min":24.89,
            "temp_max":24.89,
            "pressure":991.73,
            "sea_level":1020.07,
            "grnd_level":991.73,
            "humidity":69,
            "temp_kf":0
          },
          "weather":[
            {
              "id":500,
              "main":"Rain",
              "description":"light rain",
              "icon":"10n"
            }
          ],
          "clouds":{
            "all":56
          },
          "wind":{
            "speed":4.32,
            "deg":87.003
          },
          "rain":{
            "3h":0.06205
          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-03 15:00:00"
        },
        {
          "dt":1525370400,
          "main":{
            "temp":24.75,
            "temp_min":24.75,
            "temp_max":24.75,
            "pressure":991.55,
            "sea_level":1019.97,
            "grnd_level":991.55,
            "humidity":66,
            "temp_kf":0
          },
          "weather":[
            {
              "id":802,
              "main":"Clouds",
              "description":"scattered clouds",
              "icon":"03n"
            }
          ],
          "clouds":{
            "all":44
          },
          "wind":{
            "speed":3.76,
            "deg":80.5016
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-03 18:00:00"
        }
      ]
    },
    {
      "day":"Fri",
      "data":[
        {
          "dt":1525381200,
          "main":{
            "temp":23.51,
            "temp_min":23.51,
            "temp_max":23.51,
            "pressure":990.77,
            "sea_level":1019.2,
            "grnd_level":990.77,
            "humidity":60,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":3.12,
            "deg":82.0004
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-03 21:00:00"
        },
        {
          "dt":1525392000,
          "main":{
            "temp":22.06,
            "temp_min":22.06,
            "temp_max":22.06,
            "pressure":991.69,
            "sea_level":1020.18,
            "grnd_level":991.69,
            "humidity":63,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01n"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":3.68,
            "deg":69.5036
          },
          "rain":{

          },
          "sys":{
            "pod":"n"
          },
          "dt_txt":"2018-05-04 00:00:00"
        },
        {
          "dt":1525402800,
          "main":{
            "temp":29,
            "temp_min":29,
            "temp_max":29,
            "pressure":993.51,
            "sea_level":1022,
            "grnd_level":993.51,
            "humidity":43,
            "temp_kf":0
          },
          "weather":[
            {
              "id":800,
              "main":"Clear",
              "description":"clear sky",
              "icon":"01d"
            }
          ],
          "clouds":{
            "all":0
          },
          "wind":{
            "speed":4.82,
            "deg":91.5048
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-04 03:00:00"
        },
        {
          "dt":1525413600,
          "main":{
            "temp":34.47,
            "temp_min":34.47,
            "temp_max":34.47,
            "pressure":993.16,
            "sea_level":1021.2,
            "grnd_level":993.16,
            "humidity":38,
            "temp_kf":0
          },
          "weather":[
            {
              "id":801,
              "main":"Clouds",
              "description":"few clouds",
              "icon":"02d"
            }
          ],
          "clouds":{
            "all":12
          },
          "wind":{
            "speed":7,
            "deg":102.002
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-04 06:00:00"
        },
        {
          "dt":1525424400,
          "main":{
            "temp":37.18,
            "temp_min":37.18,
            "temp_max":37.18,
            "pressure":990.52,
            "sea_level":1018.49,
            "grnd_level":990.52,
            "humidity":32,
            "temp_kf":0
          },
          "weather":[
            {
              "id":802,
              "main":"Clouds",
              "description":"scattered clouds",
              "icon":"03d"
            }
          ],
          "clouds":{
            "all":36
          },
          "wind":{
            "speed":4.32,
            "deg":111.002
          },
          "rain":{

          },
          "sys":{
            "pod":"d"
          },
          "dt_txt":"2018-05-04 09:00:00"
        }
      ]
    }
  ];

  const dummyProps = {
    data: data,
    selectedDayName: 'sun',
    onDayClick: jest.fn(),
  };

  const wrapper = shallow(<Days {...dummyProps} />);

  it('should be defined', () => {
    expect(wrapper).toBeDefined();
  });

  it('data should not be an empty array', () => {
    const component = mount(<Days {...dummyProps} />);
    expect(!!component.props().data.length).toBe(true);
  });

  it('should call a function when click on an item', () => {
    const li = wrapper.find('li');
    li.forEach((item) => {
      item.props().onClick();
      expect(dummyProps.onDayClick).toHaveBeenCalled();
    })
  });
});